### PR TITLE
Fix #15 "An item with the same key has already been added."

### LINKED ISSUE #15: Duplicates cause "An item with the same key has already been added." exception
# Duplicates cause "An item with the same key has already been added." exception

#### Example:

```ini
root = true

[*.cs]
dotnet_sort_system_directives_first = true
dotnet_sort_system_directives_first = true
```

taken from:

- [.editorconfig#L88](https://github.com/ChilliCream/hotchocolate/blob/79f5cfdd60a5b731ae11b65c0381a42cfb90a8b7/.editorconfig#L88)
- [.editorconfig#L118](https://github.com/ChilliCream/hotchocolate/blob/79f5cfdd60a5b731ae11b65c0381a42cfb90a8b7/.editorconfig#L118)

#### Expected result:

`EditorConfigParser.GetConfigurationFilesTillRoot()` works without exceptions and probably keeps the last value if duplicates exist (as documented, if I am not mistaken).

#### Actual result:

`EditorConfigParser.GetConfigurationFilesTillRoot()` fails with "An item with the same key has already been added."

Exception details:

```
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at EditorConfig.Core.EditorConfigFile.Parse(String file)
   at EditorConfig.Core.EditorConfigFile..ctor(String file)
   at EditorConfig.Core.EditorConfigParser.<>c.<ParseConfigFilesTillRoot>b__16_0(String f)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at EditorConfig.Core.EditorConfigParser.<ParseConfigFilesTillRoot>d__16.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.<ReverseIterator>d__75`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Config.Invoke(IEditor editor, ModuleEditorEventArgs e) in ...
   at FarNet.Far0.InvokeModuleEditors(IEditor editor, Char* fileName)
```

### PR DESCRIPTION
**Pull request by nightroman**

### CODE REVIEW

**Review by Mpdreamz — APPROVED** [review]
LGTM

**Comment by nightroman** [comment]
Thank you, looking forward to the updated NuGet package!

**Comment by nightroman** [comment]
Are there any plans to release the package with the fix?

**Comment by Mpdreamz** [comment]
Aye I will try and get the fixes up next week!

**Comment by nightroman** [comment]
Could you please push the package?

**Comment by nightroman** [comment]
Dear developers. Could you please release the fix and publish the package?
Is this project abandoned?

**Comment by Mpdreamz** [comment]
It's in maintenance mode, completely dropped the ball on publishing this fix sorry. 

Will try and see if I can do so tonight

**Comment by nightroman** [comment]
@Mpdreamz Glad to know that and looking forward to the new package!

**Pull request merged**
